backend:
  # Use netlify identity as backend
  name: git-gateway
  branch: master
  ### enable below lines for github integration ###
  # name: github
  # repo: surjithctly/neat-starter
media_folder: "src/static/img"
public_folder: "/static/img"

# Please run "npx netlify-cms-proxy-server" for local backend
local_backend: true
# publish_mode: editorial_workflow
collections:
  - label: "Accueil"
    name: "home"
    editor:
      preview: false
    files:
      - label: "Image Accueil"
        name: "home-image"
        file: "src/_data/home.yaml"
        fields: 
          - label: "Image Accueil"
            name: "image"
            file: "src/_data/home.yaml"
            widget: "image"
            choose_url: false
            media_library:
              config:
              multiple: false
  - label: "Gallerie"
    name: "gallery"
    editor: 
      preview: false
    files:
      - label: "Liste d'oeuvres" 
        name: "artwork-list"
        file: "src/_data/artworks-list.json"
        extension: "json"
        fields:
          - label: "Oeuvres"
            name: "artworks"
            widget: "list"
            editor:
              preview: false
            fields: 
              - label: "Oeuvre"
                name: "image"
                widget: "image"
                choose_url: false
                media_library:
                  config:
                  multiple: false
              - label: "Tags"
                name: "tags"
                widget: "list"
                summary: '{{fields.name}}'
                field: {label: Name, name: name, widget: string}
              - { label: "Technique", name: "technique", widget: "string" }
              - { label: "Format", name: "format", widget: "string" }
              - { label: "Date", name: "date", widget: "date" }
              - widget: select
                label: "Medium"
                name: "medium"
                multiple: false
                create: true
                options: ["Peinture", "dessin"]
  - label: "Actualités"
    name: "actus"
    editor:
      preview: false
    files:
      - label: "Évènements"
        name: "events"
        file: "src/_data/events.yaml"
        fields:
          - label: "Évènement"
            name: event
            widget: list
            create: true
            editor:
              preview: false
            fields:
              - { label: "Titre", name: "title", widget: "string" }
              - { label: "Lieu", name: "location", widget: "string" }
              - { label: "Date debut", name: "startdate", widget: "date" }
              - { label: "Date fin", name: "enddate", widget: "date" }
              - { label: URL, name: url, widget: string }
              - { label: "Passée?", name: outdated, widget: boolean, default: false }
              - label: "Image"
                name: "image"
                widget: "image"
                choose_url: false
                media_library:
                  config:
                  multiple: false
  - label: "Bio"
    name: "bio"
    editor:
      preview: false
    files: 
      - label: "Biographie"
        name: "bio"
        file: "src/_data/biography.yaml"
        fields: 
          - label: "Image"
            name: "image"
            widget: "image"
            choose_url: false
            media_library:
              config:
              multiple: false
          - label: "Life Event"
            name: "lifeEvent"
            widget: list
            create: true
            editor:
              preview: false
            fields:
              - { label: "Année", name: "year", widget: "string" }
              - { label: "Description", name: "description", widget: "string" }